#!/usr/bin/env ruby
require './market.rb'
require './script/helpers.rb'
require 'erb'

years = {}
(2000..2022).each do |year|
  years[year] = simulate(:year => year).results
  years[year].each do |h|
    sell_date = h[:sell] ? h[:sell].date : h[:buy].ticker.latest_bar.date
    h[:spy] = spy(h[:buy].date, sell_date)
  end
end

years.each do |year, data|
  out = {:year   => year,
         :num    => data.size,
         :num_unsold   => data.count {|h| h[:sell].nil? },
         :num_delisted => data.count {|h| h[:delisted] },
         :hold   => data.map {|r| r[:hold] || 10000 }.median,
         :mean   => data.map {|r| r[:ROI] }.mean,
         :median => data.map {|r| r[:ROI] }.median,
         :stddev => data.map {|r| r[:ROI] }.standard_deviation,
         :spy    => data.map {|r| r[:spy] }.mean,
         :sp500  => spy(T("1 jan #{year}"), T("31 dec #{year}"))
        }
  out[:sharpe] = out[:mean] / out[:stddev]

  years[year] = out
end

out = ERB.new(File.read("views/summary.erb")).result

open("views/summary.html", "w") {|f| f.write out }

