#!/usr/bin/env ruby
require 'pry'
require './market.rb'
require './script/helpers.rb'

spy = proc do |debut, fin|
  debut = debut.is_a?(Time) ? debut : Time.parse(debut.to_s)
  fin   = fin.is_a?(Time) ? fin : Time.parse(fin.to_s)

  buy  = SPY.bars.sort_by {|b| (debut - b.date).abs }.first
  sell = SPY.bars.sort_by {|b| (fin - b.date).abs }.first

  sell.change_from buy
end

binding.pry

