#!/usr/bin/env ruby

###################################
# Option parsing
# #################################
require 'optimist'

opts = Optimist::options do
  banner "Run a sample year of investing
Usage:
  script/invest [options]
"

  opt :algorithm, "Which algorithm to use", :default => "VolatileDrop"
  opt :cached, "Use cached results"
  opt :year, "Which year to model", :type => :string
  opt :cash, "How much money to start with", :default => 10.0
  opt :pieces, "How many pieces to divy the circulating cash to", :default => 50.0
  opt :drop, "What drop to look for in a buy signal", :type => :float #, :default => -0.2
  opt :rise, "What rise to look for in a buy signal", :type => :float #, :default => 0.25
  opt :slope, "Slope for the sell curve", :short => "-m", :type => :float#, :default => -0.02
  opt :yint, "y-intercept for the sell curve", :short => "-b", :type => :float#, :default => 5.2
  opt :"no-reinvest", "Don't reinvest dividends"
  opt :debug, "Print debugging output"
end

# parse the year
# 2020
# 2018..2020
if opts[:year] =~ /\../
  opts[:year] = opts[:year].split("..").map {|p| p.to_i }
  opts[:year] = opts[:year][0]..opts[:year][1]
else
  opts[:year] = opts[:year].to_i
end

case opts[:year]
when Range
  Optimist::die "year must be >= 2000" unless opts[:year].first >= 2000
when Integer
  Optimist::die "year must be >= 2000" unless opts[:year] >= 2000
end

#####################################
# Actual simulation
#####################################

require './market.rb'
require './script/helpers.rb'

original_verbose, $VERBOSE = $VERBOSE, nil
Algorithm = eval "Algorithms::#{opts[:algorithm]}"
$VERBOSE = original_verbose

opts[:slope] ||= Algorithm.new.m
opts[:yint]  ||= Algorithm.new.b
opts[:drop]  ||= Algorithm.new.drop
opts[:rise]  ||= Algorithm.new.rise

schemes = [{:m => opts[:slope],  :b => opts[:yint]}]

sim = simulate :year => opts[:year],
               :drop => opts[:drop],
               :rise => opts[:rise],
               :m    => opts[:slope],
               :b    => opts[:yint]

puts "algorithm: #{opts[:algorithm]}"
puts "loaded #{sim.holding.size} trxs"
puts "\tyear: #{opts[:year]}"
puts "\tdrop: #{opts[:drop]}"

comparison = schemes.map do |scheme|
  unless opts[:cached]
    sim.m = scheme[:m]
    sim.b = scheme[:b]

    sim.assess_sells
  end

  sells = sim.results

  puts "stats: #{scheme.inspect} (reinvest: #{!opts[:"no-reinvest"]}, pieces: #{opts[:pieces]})"
  puts "\tmed. hold:   #{sells.map {|h| h[:hold] || 1000 }.median}"
  puts "\tmed. ROI:    #{sells.map {|h| h[:ROI] }.median}"
  puts "\tavg. ROI:    #{sells.map {|h| h[:ROI] }.mean}"
  puts "\tROI / hold:  #{sells.map {|h| h[:ROI] }.mean / sells.map {|h| h[:hold] || 1000 }.median}"

  prof = profit sells, :circulation => opts[:cash],
                       :pieces      => opts[:pieces],
                       :reinvest    => !opts[:"no-reinvest"],
                       :debug       => opts[:debug]
  puts "\tskips:       #{prof[:skips].size}"
  puts "\tprofits:     #{opts[:cash]} -> #{prof[:cash]}"
  puts "\tcirculation: #{prof[:circulation]}"

  prof
end

#require 'pry'
#binding.pry

