#!/usr/bin/env ruby

# Build all of the caches
(2008..2021).each do |year|
  `script/build_cache #{year}`
  puts "built #{year}"
end

# build the summary table
`script/build_tables`
puts "built summary table"

# now generate the HTML
(2008..2020).each do |year|
  puts `script/build_html #{year}`
end

puts `script/build_html` # for the current year

puts "HTML regenerated"

`script/publish`

