#!/usr/bin/env ruby

# Build all of the caches
(2010..2022).each do |year|
  `script/build_cache -y #{year}`
  puts "built #{year}"
end

# build the summary table
`script/build_tables`
puts "built summary table"

# now generate the HTML
(2000..2021).each do |year|
  puts `script/build_html #{year}`
end

puts `script/build_html` # for the current year

puts "HTML regenerated"

`script/publish`

